"""Compatibility shim for LLM client module.

Canonical implementation lives in distill_lib.core.llm_client.
"""

from distill_lib.core.llm_client import (
    ABC,
    APIKeyNotConfiguredError,
    AsyncOpenAI,
    CompletionResponse,
    GeminiClient,
    LLMClient,
    LOG_PREVIEW_CHARS,
    Literal,
    Message,
    ModelProvider,
    OpenAIClient,
    Optional,
    RateLimiter,
    RetryConfig,
    Tool,
    ToolCall,
    ToolChoice,
    Union,
    abstractmethod,
    asyncio,
    auto_build_client,
    build_client,
    genai,
    get_api_key_env_var,
    get_api_key_for_provider,
    get_config,
    get_default_rate_limiter,
    get_default_retry_config,
    is_retryable_error,
    json,
    logger,
    logging,
    random,
    types,
)

__all__ = [
    "ABC",
    "APIKeyNotConfiguredError",
    "AsyncOpenAI",
    "CompletionResponse",
    "GeminiClient",
    "LLMClient",
    "LOG_PREVIEW_CHARS",
    "Literal",
    "Message",
    "ModelProvider",
    "OpenAIClient",
    "Optional",
    "RateLimiter",
    "RetryConfig",
    "Tool",
    "ToolCall",
    "ToolChoice",
    "Union",
    "abstractmethod",
    "asyncio",
    "auto_build_client",
    "build_client",
    "genai",
    "get_api_key_env_var",
    "get_api_key_for_provider",
    "get_config",
    "get_default_rate_limiter",
    "get_default_retry_config",
    "is_retryable_error",
    "json",
    "logger",
    "logging",
    "random",
    "types",
]
