"""Shared constants for agent tooling and search flows."""

# search_feeds request defaults
SEARCH_FEEDS_DEFAULT_HOUR_GAP = 24
SEARCH_FEEDS_DEFAULT_LIMIT = 30
SEARCH_FEEDS_CANDIDATE_MIN = 150
SEARCH_FEEDS_CANDIDATE_MULTIPLIER = 10
SEARCH_FEEDS_CACHE_TTL_SECONDS = 180
SEARCH_FEEDS_FALLBACK_TOPN = 8
SEARCH_FEEDS_SCORE_LOG_TOPN = 5

# DB candidate controls
DEFAULT_FEED_CANDIDATE_LIMIT = 300
MAX_FEED_CANDIDATE_LIMIT = 500

# search_web defaults
SEARCH_WEB_DEFAULT_MAX_RESULTS = 8
SEARCH_WEB_PATCH_MAX_RESULTS = 5

# search_memory defaults
SEARCH_MEMORY_DEFAULT_DAYS_AGO = 14
SEARCH_MEMORY_MIN_DAYS_AGO = 1
SEARCH_MEMORY_MAX_DAYS_AGO = 365
SEARCH_MEMORY_DEFAULT_LIMIT = 10
SEARCH_MEMORY_MIN_LIMIT = 1
SEARCH_MEMORY_MAX_LIMIT = 50

# Similarity thresholds
FOCUS_SIMILARITY_THRESHOLD = 0.85
